let audios = [
    "Music/Ado - Odo.mp3",
    "Music/BITE ME (feat. Zephyrianna).m4a",
    "Music/Click.m4a",
    "Music/CYBERPUNK 2077 SOUNDTRACK - WHO'S READY FOR TOMORROW by Rat Boy & IBDY (Official Video).m4a",
    "Music/Die Mad D.m4a",
    "Music/DXRTYTYPE - Bedrock.mp3",
    "Music/FOREVER.m4a",
    "Music/Gamer Mom.m4a",
    "Music/Get Prommed _3.m4a",
    "Music/higanbanban - Override.mp3",
    "Music/Inst.ogg",
    "Music/Life Letters.m4a",
    "Music/Molina Hey Kids (Feat. Late Verlane).mp3",
    "Music/Murder Brings (Trailer Theme).m4a",
    "Music/Murder Drones.m4a",
    "Music/OST - Disassembly Required.m4a",
    "Music/PollmixaN - Серый человек.mp3",
    "Music/Sadfriendd Luga - 5star.mp3",
    "Music/Salvi, Franklin Dam - Calabria.mp3",
    "Music/Solver Uzi.m4a",
    "Music/Spiderbait - Black Betty.mp3",
    "Music/StayedGone.m4a",
    "Music/The Dark Scientist - Lunziestella.m4a",
    "Music/The Knife Dance.m4a",
    "Music/The Plot 2_ This Time Its Personal.m4a",
    "Music/The Plot.m4a",
    "Music/Unfunny Game Slowed.mp3",
    "Music/Uzi and N_ The Drone Killers.m4a",
    "Music/UZI THE DRONE KILLER.m4a",
    "Music/Vinnie Dixie - Cyberpunk 2077.mp3",
    "Music/Voices.ogg",
    "Music/Yomoti - Before Chill.mp3",
    "Music/YOURE FREAKIN GROUNDED.m4a",
    "Music/Zachz Winner - doodle Slowed.mp3"
];
export { audios };